# Site Settings
title: Wangere's Resume
#url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-6
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Joseph Ngigi Wangere
tagline: Embedded Systems Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
# summary: 'Joseph is an adept Embedded Hardware Engineer keen on Wireless Sensor Networks and the Internet of Things. 
# His experience spans Industries in FinTech, Smart Mobility, and AgriTech. He is skilled in firmware development for Embedded micro-controllers and provides Technical Leadership to cross-functional Agile teams.
# As a lifelong learner, Joseph is always pursuing challenging opportunities and self-development initiatives to achieve his full career potential.

#sidebar links
email: jngigiw@gmail.com
phone: +254725451900
#website: 
linkedin: josephngigiwangere
github: JOE-JOE-NGIGI
twitter: '@ngigiwangere'
#wechat: qianzhangqz
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
